In [3]:
li1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]

for i in li1 :
    print(i)

1
2
3
4
5
6
7
8
9

In [5]:
num = 1
while num < 1000 : 
    print(num)
    num += 1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999

In [6]:
for a in [1, 2, 3] : 
    print(a)

1
2
3

In [13]:
for a in [(1, 3), {5, 7}, 9, {1:1}] : 
    print(a)
    print(type(a))

(1, 3)
<class 'tuple'>
{5, 7}
<class 'set'>
9
<class 'int'>
{1: 1}
<class 'dict'>

In [18]:
for(a, b, c) in [(1, 2, 3), (3, 4, 5), (5, 6, 7)] :
    print ("%d + %d + %d = %d" % (a, b, c, (a + b + c)))

1 + 2 + 3 = 6
3 + 4 + 5 = 12
5 + 6 + 7 = 18

In [10]:
(a, b)  = (1, 2)
print(a, b)
print(a+b)

1 2
3

In [28]:
d_str = "hi"
d_list = [1, 2]
d_tuple = (1, 2, 3)
d_dict = {"one":1, "two":2, "three":3}
d_set = {1, 2, 3}

print("Stirng : ")
for a in d_str : 
    print(a)
    
print("-"*50)
    
print("List : ")
for a in d_list : 
    print(a)
    
print("-"*50)
    
print("Tuple : ")
for a in d_tuple :
    print(a)

print("-"*50)

print("Dictionary : ")
for a in d_dict :
    print(a)
    
print("-"*50)
   
print("Set : ")
for a in d_set : 
    print(a)
    
# Stirng : 
# h
# i
# --------------------------------------------------
# List : 
# 1
# 2
# --------------------------------------------------
# Tuple : 
# 1
# 2
# 3
# --------------------------------------------------
# Dictionary : 
# one
# two
# three
# --------------------------------------------------
# Set : 
# 1
# 2
# 3

Stirng :
h
i
--------------------------------------------------
List :
1
2
--------------------------------------------------
Tuple :
1
2
3
--------------------------------------------------
Dictionary :
one
two
three
--------------------------------------------------
Set :
1
2
3

In [31]:
num = 1
for i in range(1, 11) : 
    print(i)

1
2
3
4
5
6
7
8
9
10

a = 0
for i in range(1, 10):
    a += i
    print(a)

In [34]:
a = 0
for i in range(1, 10):
    a += i
    print(a, end = " ")

1 3 6 10 15 21 28 36 45

In [37]:
for i in range(1, 5) :
    print(i, end=" ")

1 2 3 4

In [52]:
for i in range(0, 10) : 
    print(i,  end = "")
    
print()
    
for i in range(1, 11) : 
    print(i,  end = " ")
    
print()

for i in range(1, 10, 2) : 
    print(i,  end = " ")

print()

for i in range(20, 1, -2) : 
    print(i, end=" ")
    
    
# 0123456789
# 1 2 3 4 5 6 7 8 9 10 
# 1 3 5 7 9 
# 20 18 16 14 12 10 8 6 4 2

0123456789
1 2 3 4 5 6 7 8 9 10
1 3 5 7 9
20 18 16 14 12 10 8 6 4 2

In [82]:
print("-"*50)
print("섭씨  |  화씨")
print("-"*50)

for i in range(-20, 30, 5) :
    print("%-5s|  %-5.1f" % (i , (i *1.8)+32))
    
print("-"*50)

# --------------------------------------------------
# 섭씨  |  화씨
# --------------------------------------------------
# -20  |  -4.0 
# -15  |  5.0  
# -10  |  14.0 
# -5   |  23.0 
# 0    |  32.0 
# 5    |  41.0 
# 10   |  50.0 
# 15   |  59.0 
# 20   |  68.0 
# 25   |  77.0 
# --------------------------------------------------

--------------------------------------------------
섭씨  |  화씨
--------------------------------------------------
-20  |  -4.0
-15  |  5.0
-10  |  14.0
-5   |  23.0
0    |  32.0
5    |  41.0
10   |  50.0
15   |  59.0
20   |  68.0
25   |  77.0
--------------------------------------------------

In [102]:
number = input("하이픈(-)을 포함한 휴대폰 번호를 입력하세요.")

for i in number : 
    if i != "-" :
        print(i, end="")
    
# 하이픈(-)을 포함한 휴대폰 번호를 입력하세요.010-1323-1423
# 01013231423

하이픈(-)을 포함한 휴대폰 번호를 입력하세요.010-1323-1423
01013231423

In [100]:


number = "010-1322-1323"

number.replace("0", "9")
print(number)
print(number.count("-"))

s = "정상록"
s.replace("정", "")
print(s)

print("정상정".replace("정", ""))

010-1322-1323
2
정상록
상

In [108]:
number = input("하이픈(-)을 뺀 11자리의 휴대폰 번호를 입력하세요.")

phone = ""

for i in number : 
    phone += i
    if len(phone) == 3 or len(phone) == 8 : 
        phone += "-"
        
print(phone)

# 하이픈(-)을 뺀 11자리의 휴대폰 번호를 입력하세요.01099891823
# 010-9989-1823

하이픈(-)을 뺀 11자리의 휴대폰 번호를 입력하세요.01099891823
010-9989-1823

In [113]:
number = input("하이픈(-)을 뺀 11자리의 휴대폰 번호를 입력하세요.")

phone = ""

for i in range(len(number)) : 
    phone += number[i]
    if i == 2 or i == 6 :
        phone += "-"

print(phone)

# 하이픈(-)을 뺀 11자리의 휴대폰 번호를 입력하세요.01098766789
# 010-9876-6789

하이픈(-)을 뺀 11자리의 휴대폰 번호를 입력하세요.01098766789
010-9876-6789

In [148]:
print("-"*50)
print("{:<10}{:<13}{:<10}{:<10}".format("cm", "inch", "ft", "yd"))
print("-"*50)

for cm in range(10, 201, 10) :
    print("{:<10}{:<13}{:<10}{:<10}".format(str(cm) + "cm", str(round((cm / 2.54), 2)) + "inch", str(round((cm / 30.48), 2)) + "ft", str(round((cm / 91.44), 2)) + "ft"))
    
print("-"*50)


# --------------------------------------------------
# cm        inch         ft        yd        
# --------------------------------------------------
# 10cm      3.94inch     0.33ft    0.11ft    
# 20cm      7.87inch     0.66ft    0.22ft    
# 30cm      11.81inch    0.98ft    0.33ft    
# 40cm      15.75inch    1.31ft    0.44ft    
# 50cm      19.69inch    1.64ft    0.55ft    
# 60cm      23.62inch    1.97ft    0.66ft    
# 70cm      27.56inch    2.3ft     0.77ft    
# 80cm      31.5inch     2.62ft    0.87ft    
# 90cm      35.43inch    2.95ft    0.98ft    
# 100cm     39.37inch    3.28ft    1.09ft    
# 110cm     43.31inch    3.61ft    1.2ft     
# 120cm     47.24inch    3.94ft    1.31ft    
# 130cm     51.18inch    4.27ft    1.42ft    
# 140cm     55.12inch    4.59ft    1.53ft    
# 150cm     59.06inch    4.92ft    1.64ft    
# 160cm     62.99inch    5.25ft    1.75ft    
# 170cm     66.93inch    5.58ft    1.86ft    
# 180cm     70.87inch    5.91ft    1.97ft    
# 190cm     74.8inch     6.23ft    2.08ft    
# 200cm     78.74inch    6.56ft    2.19ft    
# --------------------------------------------------

--------------------------------------------------
cm        inch         ft        yd
--------------------------------------------------
10cm      3.94inch     0.33ft    0.11ft
20cm      7.87inch     0.66ft    0.22ft
30cm      11.81inch    0.98ft    0.33ft
40cm      15.75inch    1.31ft    0.44ft
50cm      19.69inch    1.64ft    0.55ft
60cm      23.62inch    1.97ft    0.66ft
70cm      27.56inch    2.3ft     0.77ft
80cm      31.5inch     2.62ft    0.87ft
90cm      35.43inch    2.95ft    0.98ft
100cm     39.37inch    3.28ft    1.09ft
110cm     43.31inch    3.61ft    1.2ft
120cm     47.24inch    3.94ft    1.31ft
130cm     51.18inch    4.27ft    1.42ft
140cm     55.12inch    4.59ft    1.53ft
150cm     59.06inch    4.92ft    1.64ft
160cm     62.99inch    5.25ft    1.75ft
170cm     66.93inch    5.58ft    1.86ft
180cm     70.87inch    5.91ft    1.97ft
190cm     74.8inch     6.23ft    2.08ft
200cm     78.74inch    6.56ft    2.19ft
--------------------------------------------------

In [149]:
print("-"*50)
print("{:<10}{:<13}{:<10}".format("kg", "lb", "oz"))
print("-"*50)

for kg in range(10, 101, 5) :
    print("{:<10}{:<13}{:<10}".format(str(kg) + "kg", str(round((kg *2.205), 2)) + "lb", str(round((kg *35.274), 2)) + "oz"))
    
print("-"*50)

# --------------------------------------------------
# kg        lb           oz        
# --------------------------------------------------
# 10kg      22.05lb      352.74oz  
# 15kg      33.08lb      529.11oz  
# 20kg      44.1lb       705.48oz  
# 25kg      55.12lb      881.85oz  
# 30kg      66.15lb      1058.22oz 
# 35kg      77.17lb      1234.59oz 
# 40kg      88.2lb       1410.96oz 
# 45kg      99.23lb      1587.33oz 
# 50kg      110.25lb     1763.7oz  
# 55kg      121.28lb     1940.07oz 
# 60kg      132.3lb      2116.44oz 
# 65kg      143.33lb     2292.81oz 
# 70kg      154.35lb     2469.18oz 
# 75kg      165.38lb     2645.55oz 
# 80kg      176.4lb      2821.92oz 
# 85kg      187.43lb     2998.29oz 
# 90kg      198.45lb     3174.66oz 
# 95kg      209.47lb     3351.03oz 
# 100kg     220.5lb      3527.4oz  
# --------------------------------------------------

--------------------------------------------------
kg        lb           oz
--------------------------------------------------
10kg      22.05lb      352.74oz
15kg      33.08lb      529.11oz
20kg      44.1lb       705.48oz
25kg      55.12lb      881.85oz
30kg      66.15lb      1058.22oz
35kg      77.17lb      1234.59oz
40kg      88.2lb       1410.96oz
45kg      99.23lb      1587.33oz
50kg      110.25lb     1763.7oz
55kg      121.28lb     1940.07oz
60kg      132.3lb      2116.44oz
65kg      143.33lb     2292.81oz
70kg      154.35lb     2469.18oz
75kg      165.38lb     2645.55oz
80kg      176.4lb      2821.92oz
85kg      187.43lb     2998.29oz
90kg      198.45lb     3174.66oz
95kg      209.47lb     3351.03oz
100kg     220.5lb      3527.4oz
--------------------------------------------------

In [157]:
for a in range(1, 6, 1) : 
    for b in range(1, 6, 1) :
        for c in range(1, 6, 1) : 
            for d in range(1, 6, 1) :
                print(a, b, c, d)

1 1 1 1
1 1 1 2
1 1 1 3
1 1 1 4
1 1 1 5
1 1 2 1
1 1 2 2
1 1 2 3
1 1 2 4
1 1 2 5
1 1 3 1
1 1 3 2
1 1 3 3
1 1 3 4
1 1 3 5
1 1 4 1
1 1 4 2
1 1 4 3
1 1 4 4
1 1 4 5
1 1 5 1
1 1 5 2
1 1 5 3
1 1 5 4
1 1 5 5
1 2 1 1
1 2 1 2
1 2 1 3
1 2 1 4
1 2 1 5
1 2 2 1
1 2 2 2
1 2 2 3
1 2 2 4
1 2 2 5
1 2 3 1
1 2 3 2
1 2 3 3
1 2 3 4
1 2 3 5
1 2 4 1
1 2 4 2
1 2 4 3
1 2 4 4
1 2 4 5
1 2 5 1
1 2 5 2
1 2 5 3
1 2 5 4
1 2 5 5
1 3 1 1
1 3 1 2
1 3 1 3
1 3 1 4
1 3 1 5
1 3 2 1
1 3 2 2
1 3 2 3
1 3 2 4
1 3 2 5
1 3 3 1
1 3 3 2
1 3 3 3
1 3 3 4
1 3 3 5
1 3 4 1
1 3 4 2
1 3 4 3
1 3 4 4
1 3 4 5
1 3 5 1
1 3 5 2
1 3 5 3
1 3 5 4
1 3 5 5
1 4 1 1
1 4 1 2
1 4 1 3
1 4 1 4
1 4 1 5
1 4 2 1
1 4 2 2
1 4 2 3
1 4 2 4
1 4 2 5
1 4 3 1
1 4 3 2
1 4 3 3
1 4 3 4
1 4 3 5
1 4 4 1
1 4 4 2
1 4 4 3
1 4 4 4
1 4 4 5
1 4 5 1
1 4 5 2
1 4 5 3
1 4 5 4
1 4 5 5
1 5 1 1
1 5 1 2
1 5 1 3
1 5 1 4
1 5 1 5
1 5 2 1
1 5 2 2
1 5 2 3
1 5 2 4
1 5 2 5
1 5 3 1
1 5 3 2
1 5 3 3
1 5 3 4
1 5 3 5
1 5 4 1
1 5 4 2
1 5 4 3
1 5 4 4
1 5 4 5
1 5 5 1
1 5 5 2
1 5 5 3
1 5 5 4
1 5 5 5
2 1 1 1
2 1 1 2
2 1 1 3
2 1 1 4
2 1 1 5
2 1 2 1
2 1 2 2
2 1 2 3
2 1 2 4
2 1 2 5
2 1 3 1
2 1 3 2
2 1 3 3
2 1 3 4
2 1 3 5
2 1 4 1
2 1 4 2
2 1 4 3
2 1 4 4
2 1 4 5
2 1 5 1
2 1 5 2
2 1 5 3
2 1 5 4
2 1 5 5
2 2 1 1
2 2 1 2
2 2 1 3
2 2 1 4
2 2 1 5
2 2 2 1
2 2 2 2
2 2 2 3
2 2 2 4
2 2 2 5
2 2 3 1
2 2 3 2
2 2 3 3
2 2 3 4
2 2 3 5
2 2 4 1
2 2 4 2
2 2 4 3
2 2 4 4
2 2 4 5
2 2 5 1
2 2 5 2
2 2 5 3
2 2 5 4
2 2 5 5
2 3 1 1
2 3 1 2
2 3 1 3
2 3 1 4
2 3 1 5
2 3 2 1
2 3 2 2
2 3 2 3
2 3 2 4
2 3 2 5
2 3 3 1
2 3 3 2
2 3 3 3
2 3 3 4
2 3 3 5
2 3 4 1
2 3 4 2
2 3 4 3
2 3 4 4
2 3 4 5
2 3 5 1
2 3 5 2
2 3 5 3
2 3 5 4
2 3 5 5
2 4 1 1
2 4 1 2
2 4 1 3
2 4 1 4
2 4 1 5
2 4 2 1
2 4 2 2
2 4 2 3
2 4 2 4
2 4 2 5
2 4 3 1
2 4 3 2
2 4 3 3
2 4 3 4
2 4 3 5
2 4 4 1
2 4 4 2
2 4 4 3
2 4 4 4
2 4 4 5
2 4 5 1
2 4 5 2
2 4 5 3
2 4 5 4
2 4 5 5
2 5 1 1
2 5 1 2
2 5 1 3
2 5 1 4
2 5 1 5
2 5 2 1
2 5 2 2
2 5 2 3
2 5 2 4
2 5 2 5
2 5 3 1
2 5 3 2
2 5 3 3
2 5 3 4
2 5 3 5
2 5 4 1
2 5 4 2
2 5 4 3
2 5 4 4
2 5 4 5
2 5 5 1
2 5 5 2
2 5 5 3
2 5 5 4
2 5 5 5
3 1 1 1
3 1 1 2
3 1 1 3
3 1 1 4
3 1 1 5
3 1 2 1
3 1 2 2
3 1 2 3
3 1 2 4
3 1 2 5
3 1 3 1
3 1 3 2
3 1 3 3
3 1 3 4
3 1 3 5
3 1 4 1
3 1 4 2
3 1 4 3
3 1 4 4
3 1 4 5
3 1 5 1
3 1 5 2
3 1 5 3
3 1 5 4
3 1 5 5
3 2 1 1
3 2 1 2
3 2 1 3
3 2 1 4
3 2 1 5
3 2 2 1
3 2 2 2
3 2 2 3
3 2 2 4
3 2 2 5
3 2 3 1
3 2 3 2
3 2 3 3
3 2 3 4
3 2 3 5
3 2 4 1
3 2 4 2
3 2 4 3
3 2 4 4
3 2 4 5
3 2 5 1
3 2 5 2
3 2 5 3
3 2 5 4
3 2 5 5
3 3 1 1
3 3 1 2
3 3 1 3
3 3 1 4
3 3 1 5
3 3 2 1
3 3 2 2
3 3 2 3
3 3 2 4
3 3 2 5
3 3 3 1
3 3 3 2
3 3 3 3
3 3 3 4
3 3 3 5
3 3 4 1
3 3 4 2
3 3 4 3
3 3 4 4
3 3 4 5
3 3 5 1
3 3 5 2
3 3 5 3
3 3 5 4
3 3 5 5
3 4 1 1
3 4 1 2
3 4 1 3
3 4 1 4
3 4 1 5
3 4 2 1
3 4 2 2
3 4 2 3
3 4 2 4
3 4 2 5
3 4 3 1
3 4 3 2
3 4 3 3
3 4 3 4
3 4 3 5
3 4 4 1
3 4 4 2
3 4 4 3
3 4 4 4
3 4 4 5
3 4 5 1
3 4 5 2
3 4 5 3
3 4 5 4
3 4 5 5
3 5 1 1
3 5 1 2
3 5 1 3
3 5 1 4
3 5 1 5
3 5 2 1
3 5 2 2
3 5 2 3
3 5 2 4
3 5 2 5
3 5 3 1
3 5 3 2
3 5 3 3
3 5 3 4
3 5 3 5
3 5 4 1
3 5 4 2
3 5 4 3
3 5 4 4
3 5 4 5
3 5 5 1
3 5 5 2
3 5 5 3
3 5 5 4
3 5 5 5
4 1 1 1
4 1 1 2
4 1 1 3
4 1 1 4
4 1 1 5
4 1 2 1
4 1 2 2
4 1 2 3
4 1 2 4
4 1 2 5
4 1 3 1
4 1 3 2
4 1 3 3
4 1 3 4
4 1 3 5
4 1 4 1
4 1 4 2
4 1 4 3
4 1 4 4
4 1 4 5
4 1 5 1
4 1 5 2
4 1 5 3
4 1 5 4
4 1 5 5
4 2 1 1
4 2 1 2
4 2 1 3
4 2 1 4
4 2 1 5
4 2 2 1
4 2 2 2
4 2 2 3
4 2 2 4
4 2 2 5
4 2 3 1
4 2 3 2
4 2 3 3
4 2 3 4
4 2 3 5
4 2 4 1
4 2 4 2
4 2 4 3
4 2 4 4
4 2 4 5
4 2 5 1
4 2 5 2
4 2 5 3
4 2 5 4
4 2 5 5
4 3 1 1
4 3 1 2
4 3 1 3
4 3 1 4
4 3 1 5
4 3 2 1
4 3 2 2
4 3 2 3
4 3 2 4
4 3 2 5
4 3 3 1
4 3 3 2
4 3 3 3
4 3 3 4
4 3 3 5
4 3 4 1
4 3 4 2
4 3 4 3
4 3 4 4
4 3 4 5
4 3 5 1
4 3 5 2
4 3 5 3
4 3 5 4
4 3 5 5
4 4 1 1
4 4 1 2
4 4 1 3
4 4 1 4
4 4 1 5
4 4 2 1
4 4 2 2
4 4 2 3
4 4 2 4
4 4 2 5
4 4 3 1
4 4 3 2
4 4 3 3
4 4 3 4
4 4 3 5
4 4 4 1
4 4 4 2
4 4 4 3
4 4 4 4
4 4 4 5
4 4 5 1
4 4 5 2
4 4 5 3
4 4 5 4
4 4 5 5
4 5 1 1
4 5 1 2
4 5 1 3
4 5 1 4
4 5 1 5
4 5 2 1
4 5 2 2
4 5 2 3
4 5 2 4
4 5 2 5
4 5 3 1
4 5 3 2
4 5 3 3
4 5 3 4
4 5 3 5
4 5 4 1
4 5 4 2
4 5 4 3
4 5 4 4
4 5 4 5
4 5 5 1
4 5 5 2
4 5 5 3
4 5 5 4
4 5 5 5
5 1 1 1
5 1 1 2
5 1 1 3
5 1 1 4
5 1 1 5
5 1 2 1
5 1 2 2
5 1 2 3
5 1 2 4
5 1 2 5
5 1 3 1
5 1 3 2
5 1 3 3
5 1 3 4
5 1 3 5
5 1 4 1
5 1 4 2
5 1 4 3
5 1 4 4
5 1 4 5
5 1 5 1
5 1 5 2
5 1 5 3
5 1 5 4
5 1 5 5
5 2 1 1
5 2 1 2
5 2 1 3
5 2 1 4
5 2 1 5
5 2 2 1
5 2 2 2
5 2 2 3
5 2 2 4
5 2 2 5
5 2 3 1
5 2 3 2
5 2 3 3
5 2 3 4
5 2 3 5
5 2 4 1
5 2 4 2
5 2 4 3
5 2 4 4
5 2 4 5
5 2 5 1
5 2 5 2
5 2 5 3
5 2 5 4
5 2 5 5
5 3 1 1
5 3 1 2
5 3 1 3
5 3 1 4
5 3 1 5
5 3 2 1
5 3 2 2
5 3 2 3
5 3 2 4
5 3 2 5
5 3 3 1
5 3 3 2
5 3 3 3
5 3 3 4
5 3 3 5
5 3 4 1
5 3 4 2
5 3 4 3
5 3 4 4
5 3 4 5
5 3 5 1
5 3 5 2
5 3 5 3
5 3 5 4
5 3 5 5
5 4 1 1
5 4 1 2
5 4 1 3
5 4 1 4
5 4 1 5
5 4 2 1
5 4 2 2
5 4 2 3
5 4 2 4
5 4 2 5
5 4 3 1
5 4 3 2
5 4 3 3
5 4 3 4
5 4 3 5
5 4 4 1
5 4 4 2
5 4 4 3
5 4 4 4
5 4 4 5
5 4 5 1
5 4 5 2
5 4 5 3
5 4 5 4
5 4 5 5
5 5 1 1
5 5 1 2
5 5 1 3
5 5 1 4
5 5 1 5
5 5 2 1
5 5 2 2
5 5 2 3
5 5 2 4
5 5 2 5
5 5 3 1
5 5 3 2
5 5 3 3
5 5 3 4
5 5 3 5
5 5 4 1
5 5 4 2
5 5 4 3
5 5 4 4
5 5 4 5
5 5 5 1
5 5 5 2
5 5 5 3
5 5 5 4
5 5 5 5

In [169]:
for i in range(3, 28, 1): 
    print(i, end=" ")
    
print("---")

a = 3
b = 10
c = 2
li1 = []

for i in range(a, b, c):
    print(i, end=" ")
    li1.append(i)

print()
print("%d에서 %d까지 %d씩 건너뛴 총합은 %d입니다." % (a, b-1, c, sum(li1)))

# 3 5 7 9 
# 3에서 9까지 2씩 건너뛴 총합은 24입니다.

3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ---
3 5 7 9
3에서 9까지 2씩 건너뛴 총합은 24입니다.

In [171]:
li1 = [i + 1 for i in range(1, 10, 1) if i % 2 == 0]

print(li1)

[3, 5, 7, 9]

In [175]:
student = {1 : 100, 2 : 7, 3 : 75, 4 : 32}

for i in student : 
    msg = "합격" if student.get(i) >= 70 else "불합격"
    print("%d번학생은 %s입니다." % (i, msg))

1번학생은 합격입니다.
2번학생은 불합격입니다.
3번학생은 합격입니다.
4번학생은 불합격입니다.

In [186]:
student = {}

stNum = int(input("학생 수를 입력하세요 : "))

for i in range(1, stNum+1, 1) : 
    student[i] = int(input(" %d번 학생의 점수를 입력하세요(0 < 점수 < 101) : " % i ))

for i in student : 
    msg = "합격" if student.get(i) >= 70 else "불합격"
    print("%d번학생은 %s입니다." % (i, msg))
    
    
# 학생 수를 입력하세요 : 4
#  1번 학생의 점수를 입력하세요(0 < 점수 < 101) : 14
#  2번 학생의 점수를 입력하세요(0 < 점수 < 101) : 25
#  3번 학생의 점수를 입력하세요(0 < 점수 < 101) : 35
#  4번 학생의 점수를 입력하세요(0 < 점수 < 101) : 45
# 1번학생은 불합격입니다.
# 2번학생은 불합격입니다.
# 3번학생은 불합격입니다.
# 4번학생은 불합격입니다.

학생 수를 입력하세요 : 4
 1번 학생의 점수를 입력하세요(0 < 점수 < 101) : 14
 2번 학생의 점수를 입력하세요(0 < 점수 < 101) : 25
 3번 학생의 점수를 입력하세요(0 < 점수 < 101) : 35
 4번 학생의 점수를 입력하세요(0 < 점수 < 101) : 45
1번학생은 불합격입니다.
2번학생은 불합격입니다.
3번학생은 불합격입니다.
4번학생은 불합격입니다.

In [182]:
student = {}
print(type(student))

<class 'dict'>

In [187]:
result = [i * 3 for i in range(1, 6, 1)]
print(result)

[3, 6, 9, 12, 15]

In [188]:
li1 = [1, 2, 3, 4, 5]
result = [i * 3 for i in li1]
print(result)

[3, 6, 9, 12, 15]

In [190]:
li1 = [1, 2, 3, 4, 5]
result = [i * 3 for i in li1 if i % 2 ==0]
print(result)

[6, 12]

In [195]:
num = 0
for i in range(1, 11, 1):
    num += i
    
print(num)

1
3
6
10
15
21
28
36
45
55
55

In [204]:
start = int(input("시작 값을 입력하세요 : "))
end = int(input("끝의 값을 입력하세요 (시작 값보다 커야함) : "))
sel = input("짝수와 홀수 중 선택하여 입력하세요 : ")
result = 0

if sel == "짝수" : 
    li1 = [i for i in range(start, end, 1) if i % 2 == 0]
elif sel == "홀수" :
    li1 = [i for i in range(start, end, 1) if i % 2 == 1]
    
result = sum(li1)

print("%d부터 %d까지 %s의 합은 %d 입니다. " % (start, end, sel, result))


# 시작 값을 입력하세요 : 2
# 끝의 값을 입력하세요 (시작 값보다 커야함) : 100
# 짝수와 홀수 중 선택하여 입력하세요 : 홀수
# 2부터 100까지 홀수의 합은 2499 입니다.

시작 값을 입력하세요 : 1
끝의 값을 입력하세요 (시작 값보다 커야함) : 100
짝수와 홀수 중 선택하여 입력하세요 : 홀수
1부터 100까지 홀수의 합은 2500 입니다.

In [202]:
li1 = [i for i in range(1, 101, 1) if i % 3 == 0 or i % 7 == 0]

result = sum(li1)
print(result)

2208

In [226]:
for i in range(2, 10, 1) :
    print("%d단" % i, end = " :")
    for x in range(1, 10, 1) :
        print("{:>3}".format(i*x), end = " ")
    print()
    
# 2단 :  2   4   6   8  10  12  14  16  18 
# 3단 :  3   6   9  12  15  18  21  24  27 
# 4단 :  4   8  12  16  20  24  28  32  36 
# 5단 :  5  10  15  20  25  30  35  40  45 
# 6단 :  6  12  18  24  30  36  42  48  54 
# 7단 :  7  14  21  28  35  42  49  56  63 
# 8단 :  8  16  24  32  40  48  56  64  72 
# 9단 :  9  18  27  36  45  54  63  72  81

2단 :  2   4   6   8  10  12  14  16  18
3단 :  3   6   9  12  15  18  21  24  27
4단 :  4   8  12  16  20  24  28  32  36
5단 :  5  10  15  20  25  30  35  40  45
6단 :  6  12  18  24  30  36  42  48  54
7단 :  7  14  21  28  35  42  49  56  63
8단 :  8  16  24  32  40  48  56  64  72
9단 :  9  18  27  36  45  54  63  72  81

In [230]:
for i in range(2, 10, 1) :
    print("%d단 " % (i))
    for x in range(1, 10, 1) :
        print("%d * %d = %d" % (i, x, (i*x)))
    print()

2단
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18

3단
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27

4단
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36

5단
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45

6단
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54

7단
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63

8단
8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72

9단
9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81

In [304]:
for i in range(1, 10) :
    for y in range(1, i+1) : 
        print("{:<1}".format("*"), end = "")
    print()
    
    
# *
# **
# ***
# ****
# *****
# ******
# *******
# ********
# *********

*
**
***
****
*****
******
*******
********
*********

In [303]:
for i in range(1, 10) : 
    for y in range(1, 11-i) :
        print(" ", end="")
    for k in range(1, 1+i) : 
        print("*", end="")
    print()
        
#          *
#         **
#        ***
#       ****
#      *****
#     ******
#    *******
#   ********
#  *********

         *
        **
       ***
      ****
     *****
    ******
   *******
  ********
 *********

In [359]:
seats = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 1, 1, 0, 1, 1, 0, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]



for i in range(0, len(seats)) : 
    for y in range(0, len(seats[0])) : 
        if seats[i][y] == 1 :
            print("■", end="")
        else :
            print("□", end="")
    print()
            


# □□□□□□□□□□
# □□□□□□□□□□
# □□□□□■□□□□
# □□□□□□□□□□
# □□□□□□□□□□
# □□□□□■□□□□
# □□□□□□□□□□
# □□□□□□□□□□
# ■□■■□■■□■■
# □□□□□□□□□□

□□□□□□□□□□
□□□□□□□□□□
□□□□□■□□□□
□□□□□□□□□□
□□□□□□□□□□
□□□□□■□□□□
□□□□□□□□□□
□□□□□□□□□□
■□■■□■■□■■
□□□□□□□□□□

In [366]:
seats = [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

li2 = []
li3 = []


for i in range(0, len(seats)) : 
    for y in range(0, len(seats[0])) : 
        if seats[i][y] == 1 :
            li3.append("■")
        else :
            li3.append("□")
    li2.append(li3)
            
print(len(seats), len(seats[2]))
print(len(li2), len(li2[2]))

for i in range(0, len(li2)) : 
    for y in range(0, len(li2[0])) : 
        print(li2[i][y], end="")
    print()

10 10
10 100
□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□■■■■■■■■■■□□□□□□□□□□
□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□■■■■■■■■■■□□□□□□□□□□
□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□■■■■■■■■■■□□□□□□□□□□
□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□■■■■■■■■■■□□□□□□□□□□
□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□■■■■■■■■■■□□□□□□□□□□
□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□■■■■■■■■■■□□□□□□□□□□
□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□■■■■■■■■■■□□□□□□□□□□
□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□■■■■■■■■■■□□□□□□□□□□
□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□■■■■■■■■■■□□□□□□□□□□
□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□■■■■■■■■■■□□□□□□□□□□

In [373]:
name_list = ["홍", "박", "Kim"]

for no, name in enumerate(name_list) : 
    print("no:%d, name:%s" % (no, name))

no:0, name:홍
no:1, name:박
no:2, name:Kim

In [371]:
name = ["길동", "철수", "형석"]
no = [1, 2, 3]

for a, b in zip(name, no) : 
    print(a, b)

길동 1
철수 2
형석 3